### ISSUE TITLE
Favicon not loading

### ISSUE THREAD

**Issue by jodri-code** [CKStudios2018/OpenSource-uTube#3]
The Favicon is not loading.
Also, much CSS Formatting is needed, everything is currently just auto-aligned top-to-bottom. I suggest looking at [ByeMC's Repo](https://github.com/ByeMC/OpenSource-uTube)

**Comment by ByeMC** [comment]
*See Also: #2*

**Comment by CKStudios2018** [comment]
We fixed the Facicon, next up is the CSS
