### ISSUE TITLE
Favico Transparency

### ISSUE THREAD

**Issue by CKStudios2018** [CKStudios2018/OpenSource-uTube#5]
**Is your feature request related to a problem? Please describe.**
Yes. The icon/favicon original file has a background, [ByeMC's version](https://github.com/ByeMC/OpenSource-uTube) has none.

**Describe the solution you'd like**
The white background removed. ByeMC, could pass the image, or simply PS it again.

**Comment by jodri-code** [comment]
do it yourself, your good in PS anyways.
while your at itm change it up. Google will find any possible way to sue your ass, using a logo similar to Google Play's will give them enough leverage to attempt something.

**Comment by ByeMC** [comment]
> **Is your feature request related to a problem? Please describe.**
> Yes. The icon/favicon original file has a background, [ByeMC's version](https://github.com/ByeMC/OpenSource-uTube) has none.
> 
> **Describe the solution you'd like**
> The white background removed. ByeMC, could pass the image, or simply PS it again.

just merge my branch (when i finish the conflicts, gimmie a sec)

**Comment by ByeMC** [comment]
whoops, deleted branch
will refork, and fix problems

**Comment by CKStudios2018** [comment]
Fixed
