### ISSUE TITLE
uTube channel (using gh)

### ISSUE THREAD

**Issue by redir110** [CKStudios2018/OpenSource-uTube#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can be made temporary; I  would like to see people have a channel section they can visit.

**Describe alternatives you've considered**
Using yt's google default.

**Comment by CKStudios2018** [comment]
we won't add this for a while

**Comment by TallerThanShort** [comment]
This should have been closed a while ago..
