### ISSUE TITLE
CSS not fully loading

### ISSUE THREAD

**Issue by CKStudios2018** [CKStudios2018/OpenSource-uTube#9]
**Describe the bug**
CSS files are being detected, but not read.

**To View Proof**
Steps to view the behavior:
1. Go to the main site
2. Press ctrl+shift+i to open debug tools
3. Click over to the 'Sources' tab
4. (optinal) you may have to click on the s/desktop/something folder
5. See CSS files, even correct names, but no CSS is inside the files.

**Expected behavior**
The files aren't expected to be loading as blank files, as they _**do**_ have content inside them.

**Screenshots**
![for thise](https://user-images.githubusercontent.com/75259904/120103700-2c057900-c151-11eb-8898-a5b5da9af110.png)
![Screenshot 2021-05-30 141536](https://user-images.githubusercontent.com/75259904/120103733-53f4dc80-c151-11eb-906e-b841f3e0a1df.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, MSEdge ('21 Edition)
 - Version, latest Chrome, Edge '21 Ed.

**Smartphone (please complete the following information):**
 - Device: Samsung S8, InnJoo Netsurfer, Nokia 3, iPhone 8
 - OS: Android 9, 10 and 10+ (respectively), iOS 14.3
 - Browser Stock Android Browser, Chrome Android, Chrome Apple, Safari

**Comment by CKStudios2018** [comment]
**Possible fix found:**
We need to make GitHub understand that the /s/ folder, and all it's contents are top priority in the site, and that the HTML is to be loaded afterwards

**Comment by ByeMC** [comment]
Put here

![image](https://user-images.githubusercontent.com/77801870/120104396-2a858200-c14c-11eb-8249-f73e1ae8610f.jpeg)

**Comment by ByeMC** [comment]
Before the /s/

**Comment by ByeMC** [comment]
Appears to be fixed, but issue was never closed, so I'll be nice and clode it for you guys
